// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

package cn.raincoding.hello.grpc.service;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.raincoding.hello.grpc.service.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string greeting = 1;</code>
   */
  java.lang.String getGreeting();
  /**
   * <code>optional string greeting = 1;</code>
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
